name = "thelazy-imgs-retention-cleaner"
main = "index.js"
compatibility_date = "2026-10-07"
workers_dev = false
preview_urls = false

[vars]
IMGBED_URL = "https://thelazy-imgs.pages.dev"

[triggers]
crons = ["* * * * *"]

[observability]
enabled = true
