name = "thelazy-imgs-retention-cleaner"
main = "index.js"
compatibility_date = "2026-10-07"
workers_dev = false
preview_urls = false

[vars]
IMGBED_URL = "https://imgs.thelazystudio.net"

[triggers]
crons = ["0 0 * * *"] # Daily at 00:00 UTC (08:00 Hong Kong).

[observability]
enabled = true
